/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.algebra;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.Article;
import hr.algebra.model.ArticleArchive;
import hr.algebra.model.ArticleTableModel;
import hr.algebra.model.Person;
import hr.algebra.model.User;
import hr.algebra.utilities.FileUtils;
import hr.algebra.utilities.IconUtils;
import hr.algebra.utilities.JAXBUtils;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.AdminDialog;
import hr.algebra.view.Login;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.text.JTextComponent;
import javax.xml.bind.JAXBException;

/**
 *
 * @author lukam
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() throws Exception {
        initAuth();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        lblErrorTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfLink = new javax.swing.JTextField();
        lblErrorLink = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPDate = new javax.swing.JTextField();
        lblErrorPDate = new javax.swing.JLabel();
        lblErrorContributor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfCreator = new javax.swing.JTextField();
        lblErrorCreator = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfContributor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDesc = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taContent = new javax.swing.JTextArea();
        lblErrorDesc = new javax.swing.JLabel();
        lblErrorContent = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArticle = new javax.swing.JTable();
        lblErrorPicPath = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        tfPicturePath = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnChoose = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuItemPrint = new javax.swing.JMenu();
        menuItemExport = new javax.swing.JMenu();
        menuItemHelp = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Title");

        lblErrorTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorTitle.setText("X");

        jLabel3.setText("Link");

        lblErrorLink.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorLink.setText("X");

        jLabel5.setText("Published date");

        lblErrorPDate.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorPDate.setText("X");

        lblErrorContributor.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorContributor.setText("X");

        jLabel8.setText("Creator");

        lblErrorCreator.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorCreator.setText("X");

        jLabel10.setText("Contributors");

        jLabel11.setText("Desc");

        taDesc.setColumns(20);
        taDesc.setRows(5);
        jScrollPane1.setViewportView(taDesc);

        jLabel12.setText("Content");

        taContent.setColumns(20);
        taContent.setRows(5);
        jScrollPane2.setViewportView(taContent);

        lblErrorDesc.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorDesc.setText("X");

        lblErrorContent.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorContent.setText("X");

        tbArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbArticle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbArticleMouseClicked(evt);
            }
        });
        tbArticle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbArticleKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbArticle);

        lblErrorPicPath.setForeground(new java.awt.Color(255, 0, 51));
        lblErrorPicPath.setText("X");

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no_image.png"))); // NOI18N

        tfPicturePath.setEditable(false);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        menuItemPrint.setText("Menu print");
        menuItemPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemPrintMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuItemPrint);

        menuItemExport.setText("Export");
        menuItemExport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemExportMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuItemExport);

        menuItemHelp.setText("Help");
        menuItemHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItemHelpMouseClicked(evt);
            }
        });
        jMenuBar2.add(menuItemHelp);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorContent)
                        .addGap(50, 50, 50)
                        .addComponent(lblErrorPicPath, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(60, 60, 60)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDelete)
                                .addGap(44, 44, 44)
                                .addComponent(btnChoose))
                            .addComponent(tfPicturePath))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfContributor, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorContributor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(tfCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblErrorCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblErrorDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblErrorLink, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblErrorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfPDate, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorPDate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
            .addComponent(jScrollPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorTitle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorLink))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorPDate)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfCreator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorCreator))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfContributor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorContributor))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(lblErrorDesc)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblErrorContent)
                            .addComponent(lblErrorPicPath)
                            .addComponent(tfPicturePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)
                            .addComponent(btnChoose)
                            .addComponent(btnAdd))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!formValid()) {
            System.out.println("Error");
            return;
        }

        try {
            String localPath = uploadPicture();

            /*Creator check*/
            Person creator = new Person();
            String fullName = tfCreator.getText().trim();
            String[] nameParts = fullName.split(" ");

            if (nameParts.length >= 2) {
                String inputName = nameParts[0];
                String inputSurname = nameParts[1];

                List<Person> people = repository.selectPeople();

                for (Person person : people) {
                    if (person.getName().equalsIgnoreCase(inputName)
                            && person.getSurname().equalsIgnoreCase(inputSurname)) {
                        creator = person;
                        break;
                    } else {
                        Person newPerson = new Person(inputName, inputSurname);
                        int idPerson = repository.createPerson(newPerson);
                        newPerson.setId(idPerson);
                        creator = newPerson;
                    }
                }
            }

            Article article = new Article(
                    tfTitle.getText().trim(),
                    tfLink.getText().trim(),
                    taDesc.getText().trim(),
                    LocalDateTime.parse(
                            tfPDate.getText().trim(),
                            Article.DATE_FORMATTER
                    ),
                    creator,
                    localPath,
                    taContent.getText().trim()
            );

            int idA = repository.createArticle(article);
            article.setId(idA);
            /*Contributor check*/
            String contributorsText = tfContributor.getText().trim();
            List<Person> existingContributors = new ArrayList<>();
            List<Person> newContributors = new ArrayList<>();
            List<Integer> contributorIds = new ArrayList<>();

            if (!contributorsText.isEmpty()) {
                String[] names = contributorsText.split(", ");

                List<Person> peopleInDb = repository.selectPeople();

                for (String full_Name : names) {
                    String[] parts = full_Name.trim().split(" ");
                    if (parts.length >= 2) {
                        String name = parts[0];
                        String surname = parts[1];

                        Optional<Person> match = peopleInDb.stream()
                                .filter(p -> p.getName().equalsIgnoreCase(name)
                                && p.getSurname().equalsIgnoreCase(surname))
                                .findFirst();

                        if (match.isPresent()) {
                            existingContributors.add(match.get());
                        } else {
                            newContributors.add(new Person(name, surname));
                        }
                    } else {
                        System.err.println("Invalid contributor name: " + full_Name);
                    }
                }

                List<Integer> newContributorIds = repository.createPeople(newContributors);

                contributorIds.addAll(
                        existingContributors.stream()
                                .map(Person::getId)
                                .collect(Collectors.toList())
                );
                contributorIds.addAll(newContributorIds);
                repository.insertArticleContributor(article.getId(), contributorIds);
            }

            List<Person> finalContributors = new ArrayList<>();

            for (Integer id : contributorIds) {
                repository.selectPerson(id).ifPresent(finalContributors::add);
            }

            article.setContributors(finalContributors);
            model.setArticles(repository.selectArticles());
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        Optional<File> optionalFile = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");

        if (optionalFile.isEmpty()) {
            return;
        }

        File file = optionalFile.get();
        tfPicturePath.setText(file.getAbsolutePath());
        setIcon(lblIcon, file);
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedArticle == null) {
            MessageUtils.showInformationMessage("INFO", "Please select an Article!");
            return;
        }

        if (!formValid()) {
            return;
        }

        try {

            if (!tfPicturePath.getText().trim().equals(selectedArticle.getPicturePath())) {
                if (Files.exists(Paths.get(selectedArticle.getPicturePath()))) {
                    Files.deleteIfExists(Paths.get(selectedArticle.getPicturePath()));
                }
                String localPath = uploadPicture();
                selectedArticle.setPicturePath(localPath);
            }

            selectedArticle.setTitle(tfTitle.getText().trim());
            selectedArticle.setLink(tfLink.getText().trim());
            selectedArticle.setDescription(taDesc.getText().trim());
            selectedArticle.setPublishedDate(LocalDateTime.parse(
                    tfPDate.getText().trim(),
                    Article.DATE_FORMATTER
            ));
            selectedArticle.setContent(taContent.getText().trim());

            /*Creator check*/
            String fullName = tfCreator.getText().trim();
            String[] nameParts = fullName.split(" ");

            if (nameParts.length >= 2) {
                String inputName = nameParts[0];
                String inputSurname = nameParts[1];

                List<Person> people = repository.selectPeople();

                for (Person person : people) {
                    if (person.getName().equalsIgnoreCase(inputName)
                            && person.getSurname().equalsIgnoreCase(inputSurname)) {
                        selectedArticle.setCreator(person);
                        break;
                    } else {
                        Person newPerson = new Person(inputName, inputSurname);
                        int idPerson = repository.createPerson(newPerson);
                        newPerson.setId(idPerson);
                        selectedArticle.setCreator(newPerson);
                        break;
                    }
                }
            }

            /* Contributor check */
            String contributorsText = tfContributor.getText().trim();

            List<Person> existingContributors = repository.getArticleContributors(selectedArticle.getId());
            List<Integer> existingContributorIds = existingContributors.stream()
                    .map(Person::getId)
                    .collect(Collectors.toList());

            List<Person> peopleInDb = repository.selectPeople();
            List<Person> newContributors = new ArrayList<>();
            List<Person> matchedContributors = new ArrayList<>();

            if (!contributorsText.isEmpty()) {
                String[] names = contributorsText.split(", ");

                for (String full_Name : names) {
                    String[] parts = full_Name.trim().split(" ");
                    if (parts.length >= 2) {
                        String name = parts[0];
                        String surname = parts[1];

                        Optional<Person> match = peopleInDb.stream()
                                .filter(p -> p.getName().equalsIgnoreCase(name)
                                && p.getSurname().equalsIgnoreCase(surname))
                                .findFirst();

                        if (match.isPresent()) {
                            matchedContributors.add(match.get());
                        } else {
                            newContributors.add(new Person(name, surname));
                        }
                    } else {
                        System.err.println("Invalid contributor name: " + full_Name);
                    }
                }
            }

            List<Integer> newContributorIds = repository.createPeople(newContributors);

            List<Integer> allNewIds = new ArrayList<>();
            allNewIds.addAll(matchedContributors.stream()
                    .map(Person::getId)
                    .collect(Collectors.toList()));
            allNewIds.addAll(newContributorIds);

            List<Integer> toRemove = new ArrayList<>(existingContributorIds);
            toRemove.removeAll(allNewIds);

            List<Integer> toAdd = new ArrayList<>(allNewIds);
            toAdd.removeAll(existingContributorIds);

            if (!toRemove.isEmpty()) {
                repository.deleteArticleContributor(selectedArticle.getId(), toRemove);
            }

            if (!toAdd.isEmpty()) {
                repository.insertArticleContributor(selectedArticle.getId(), toAdd);
            }

            List<Person> finalContributors = new ArrayList<>();

            for (Integer id : allNewIds) {
                repository.selectPerson(id).ifPresent(finalContributors::add);
            }

            selectedArticle.setContributors(finalContributors);

            repository.updateArticle(selectedArticle.getId(), selectedArticle);
            model.setArticles(repository.selectArticles());
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedArticle == null) {
            MessageUtils.showInformationMessage("INFO", "Please select an Article!");
            return;
        }

        try {

            if (Files.exists(Paths.get(selectedArticle.getPicturePath()))) {
                Files.deleteIfExists(Paths.get(selectedArticle.getPicturePath()));
            }

            List<Person> cont = repository.getArticleContributors(selectedArticle.getId());

            List<Integer> cont_Ids = cont.stream()
                    .map(Person::getId)
                    .collect(Collectors.toList());

            repository.deleteArticleContributor(selectedArticle.getId(), cont_Ids);
            repository.deleteArticle(selectedArticle.getId());
            model.setArticles(repository.selectArticles());
            clearForm();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbArticleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbArticleKeyReleased
       selectArticle();
    }//GEN-LAST:event_tbArticleKeyReleased

    private void tbArticleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbArticleMouseClicked
        selectArticle();
    }//GEN-LAST:event_tbArticleMouseClicked

    private void menuItemPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemPrintMouseClicked
        PrinterJob job = PrinterJob.getPrinterJob();

        if (job.printDialog()) {
            try {
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_menuItemPrintMouseClicked

    private void menuItemExportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemExportMouseClicked
        List<Article> listA = null;
        try {
            listA = repository.selectArticles();
        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (listA != null) {
            try {
                JAXBUtils.save(new ArticleArchive(listA), "src/main/resources/articlearchive.xml");
            } catch (JAXBException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            MessageUtils.showErrorMessage("Error", "Failed to export articles. See logs for details.");
        }
    }//GEN-LAST:event_menuItemExportMouseClicked

    private void menuItemHelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemHelpMouseClicked
        MessageUtils.showInformationMessage("Content saving function.", "Vresion 1.0");
    }//GEN-LAST:event_menuItemHelpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainWindow().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblErrorContent;
    private javax.swing.JLabel lblErrorContributor;
    private javax.swing.JLabel lblErrorCreator;
    private javax.swing.JLabel lblErrorDesc;
    private javax.swing.JLabel lblErrorLink;
    private javax.swing.JLabel lblErrorPDate;
    private javax.swing.JLabel lblErrorPicPath;
    private javax.swing.JLabel lblErrorTitle;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JMenu menuItemExport;
    private javax.swing.JMenu menuItemHelp;
    private javax.swing.JMenu menuItemPrint;
    private javax.swing.JTextArea taContent;
    private javax.swing.JTextArea taDesc;
    private javax.swing.JTable tbArticle;
    private javax.swing.JTextField tfContributor;
    private javax.swing.JTextField tfCreator;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfPDate;
    private javax.swing.JTextField tfPicturePath;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables

    private void initAuth() throws Exception {
    java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
    new Login(parent, true, this).setVisible(true);
        
    }
    
    private User currentUser;

    public void onAuthenticationSuccess(User user) throws Exception {
        this.currentUser = user;

        if (user.getIsAdmin()) {
            initAdminDialog(); // Admin
            dispose();
            initComponents();
            init();

        } else {
            initComponents(); // Regular user 
            init();
        }
    }
    

    private void initAdminDialog() throws Exception {
        java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        new AdminDialog(this, true, this).setVisible(true);

    }
    
    
    //glavni crud za mainwindow (mainwindow functions)
    
    private void fillForm(Article article) {
        tfTitle.setText(article.getTitle());
        tfLink.setText(article.getLink());
        tfPDate.setText(article.getPublishedDate().format(Article.DATE_FORMATTER));
        tfCreator.setText(article.getCreator().toString());

        List<Person> contributors = article.getContributors();
        String contributorsStr = contributors.stream()
                .map(p -> p.getName() + " " + p.getSurname())
                .collect(Collectors.joining(", "));

        tfContributor.setText(contributorsStr);
        taDesc.setText(article.getDescription());
        taContent.setText(article.getContent());
        if (article.getPicturePath() == null) {
            tfPicturePath.setText("");
            lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no_image.png")));
        } else {
            tfPicturePath.setText(article.getPicturePath());
            setIcon(lblIcon, new File(article.getPicturePath()));
        }
    }
    
    private String uploadPicture() throws IOException {
        String source = tfPicturePath.getText();
        String ext = source.substring(source.lastIndexOf("."));
        String name = UUID.randomUUID().toString() + ext;

        String destination = DIR + File.separator + name;

        FileUtils.copy(source, destination);

        return destination;
    }
    private static final String DIR = "assets";
    
    private void setIcon(JLabel label, File file) {
        try {
            label.setIcon(IconUtils.createIcon(file, label.getWidth(), label.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to set icon!");
        }
    }

    private List<JTextComponent> validationFields;
    private List<JLabel> errorLabels;

    private Repository repository;
    private ArticleTableModel model;

    private Article selectedArticle;
    private ArrayList<Person> selectedPeople = new ArrayList();

    private void init() {
        try {
            initValidation();
            hideErrors();
            initRepository();
            initTable();
        } catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Unrecoverable error", "Cannot initiate the form");
            System.exit(1);
        }
    }

    private void initRepository() throws Exception {
        repository = RepositoryFactory.getRepository();
    }

    private void initTable() throws Exception {
        tbArticle.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbArticle.setAutoCreateRowSorter(true);
        tbArticle.setRowHeight(25);
        model = new ArticleTableModel(repository.selectArticles());
        tbArticle.setModel(model);
    }

    private void initValidation() {
        validationFields = Arrays.asList(
                tfTitle,
                tfLink,
                tfPDate,
                tfCreator,
                tfContributor,
                taDesc,
                taContent,
                tfPicturePath
        );
        errorLabels = Arrays.asList(
                lblErrorTitle,
                lblErrorLink,
                lblErrorPDate,
                lblErrorCreator,
                lblErrorContributor,
                lblErrorDesc,
                lblErrorContent,
                lblErrorPicPath
        );
    }

    private void hideErrors() {
        errorLabels.forEach(e -> e.setVisible(false));
    }

    private boolean formValid() {
        hideErrors();
        boolean ok = true;

        for (int i = 0; i < validationFields.size(); i++) {
            ok &= !validationFields.get(i).getText().trim().isEmpty();
            errorLabels.get(i).setVisible(validationFields.get(i).getText().trim().isEmpty());

            if ("DATE".equals(validationFields.get(i).getName())) {
                try {
                    LocalDateTime.parse(
                            validationFields.get(i).getText().trim(),
                            Article.DATE_FORMATTER
                    );
                } catch (Exception e) {
                    ok = false;
                    errorLabels.get(i).setVisible(true);
                }
            }
        }
        return ok;
    }

    private void clearForm() {
        hideErrors();
        validationFields.forEach(e -> e.setText(""));
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/no_image.png")));
        selectedArticle = null;
    }
    
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {                                    
        init();
    }
    
    private void selectArticle() {
        int selectedRow = tbArticle.getSelectedRow();
        int rowIndex = tbArticle.convertRowIndexToModel(selectedRow);

        int id = (int) model.getValueAt(rowIndex, 0);

        try {
            Optional<Article> opt = repository.selectArticle(id);
            if (opt.isPresent()) {
                selectedArticle = opt.get();
                List<Person> neo = repository.getArticleContributors(id);
                selectedArticle.setContributors(neo);
                fillForm(selectedArticle);
            }
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }
    
}
